language: python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install -q errbot pytest pytest-pep8 pytest-cov codecov --use-wheel

script:
  - py.test --cov whydbot

after_success:
  - codecov

notifications:
  email: false
